version: '3'
services:

  db:
    image: mongo:4.2.8
    container_name: db
    ports:
     - "4000:27017"
    restart: always

  aws-s3:
    image: aws-s3
    build: 
      context: ./aws-s3
      dockerfile: Dockerfile
    container_name: video-storage
    ports:
     - "4001:80"
    environment:
      - PORT=80
      - AWS_ACCESS_KEY=AKIASVI7VPSFDYFGK24R
      - AWS_SECRET_KEY=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
    restart: "no"

  video-streaming:
    image: video-streaming
    build: 
      context: ./video-streaming
      dockerfile: Dockerfile
    container_name: video-streaming
    ports:
     - "4002:80"
    environment:
      - PORT=80
      - DBHOST=mongodb://db:27017
      - DBNAME=video-streaming
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
    depends_on:
      - db
    restart: "no"